---
apiVersion: v1
kind: Service
metadata:
  name: karthik-service
  labels:
    app: karthiknginx
    service: karthik-service
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: karthiknginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karthikdeployment
  labels:
    app: karthiknginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karthiknginx
  template:
    metadata:
      labels:
        app: karthiknginx
    spec:
      containers:
      - name: karthiknginx
        image: karthiksaigummalapu/ngnix:v1
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: karthik-service
      imagePullSecrets:
      - name: karthik-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karthik-service
data:
  x: "karthik1"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: 2886795274-30000-ollie02.environments.katacoda.com
  - http:
      paths:   
      - path: /nginx
        backend:
          serviceName: karthik-service
          servicePort: 80
